import type { z } from 'zod';
import type { BuildSchema } from './schema';

type Build = z.infer<typeof BuildSchema>;

export const builds: Build[] = [
  {
    slug: 'fair-roads',
    title: 'fair-roads',
    oneLine: 'A road-mapping model for humanitarian volunteers — and what its own numbers said to build next.',
    description: 'Volunteers map roads by hand where no usable map exists. This model does the first pass, and the interesting part is what measuring it honestly changed.',
    dates: 'Sept 2026 · proposal submitted',
    liveUrl: 'https://huggingface.co/tarabird90/dinov2s-roads',
    liveLabel: 'Model card ↗',
    status: 'wip',
    statusLabel: 'PROPOSAL SUBMITTED',
    screenshot: '/screenshots/fair-roads-fair-ui.jpg',
    gradientHeader: 'linear-gradient(135deg, #0d2820 0%, #5b4380 100%)',
    stack: ['DINOv2 ViT-S/14', 'UPerNet', 'ONNX'],
  },
  {
    slug: 'severance',
    title: 'Layoff Calculator',
    oneLine: 'A free, source-cited tool that grades severance offers.',
    description: 'A free, source-cited tool that grades severance offers and estimates runway in sixty seconds.',
    dates: '2026 → ongoing',
    liveUrl: 'https://layoffcalculator.com',
    liveLabel: 'Visit ↗',
    status: 'live',
    screenshot: '/screenshots/severance-hero.png',
    gradientHeader: 'linear-gradient(135deg, #0d2820 0%, #1a4a3a 100%)',
    stack: ['Next.js', 'TypeScript', 'Supabase'],
  },
  {
    slug: 'rollcall',
    title: 'Rollcall',
    oneLine: 'A training log and community for jiu-jitsu practitioners.',
    description: 'A training log and community for jiu-jitsu practitioners. Tracks belts, drills, and the people you roll with.',
    dates: '2026 → ongoing',
    liveUrl: 'https://www.meetwithrollcall.com/u/tara',
    liveLabel: 'Visit ↗',
    status: 'live',
    screenshot: '/screenshots/rollcall-profile.jpg',
    gradientHeader: 'linear-gradient(135deg, #fef9f0 0%, #f3eef8 100%)',
    stack: ['Next.js', 'Supabase', 'Playwright'],
  },
  {
    slug: 'knock-it-off',
    title: 'Knock It Off',
    oneLine: 'A tap-and-knock game where a cat shoves food off the counter.',
    description: 'A tap-and-knock game where a cat shoves food off the counter to a hungry dog. Built in Godot, mostly for my kids.',
    dates: '2026 · live',
    liveUrl: 'https://knock-it-off.vercel.app',
    liveLabel: 'Play ↗',
    status: 'kids',
    screenshot: '/screenshots/knock-it-off-cat-select.jpg',
    gradientHeader: 'linear-gradient(180deg, #8a6f5a 0%, #5b3a2a 100%)',
    stack: ['Godot 4.6', 'GDScript'],
  },
];
